spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_fast
    username: username
    password: password
    driver-class-name: org.postgresql.Driver # gerer par defaut par spring
  jpa:
    hibernate:
      ddl-auto: update # chn bghit ndir fach nstarter app
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: med
    password: bch
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:  #niveau de securite
          enabled: true
        connectiontimeout: 5000  #5sec
        timeout: 3000
        writetimeout: 5000
