version: '3.8'

services:

  postgres:
    container_name: postgres-sql-bf
    image: postgres
    environment:
      POSTGRES_USER: Mohammed
      POSTGRES_PASSWORD: med2002
      POSTGRES_DB: book_fast
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - spring-fast
    restart: unless-stopped


  mail-dev:
    container_name: mail-dev-bf
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - spring-fast


networks:
  spring-fast:
    driver: bridge


volumes:
  postgres:
    driver: local